version: '3.8'

services:
  app:
    build: .
    container_name: gaslit-af-warstack
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=src/frontend/app.py
      - FLASK_ENV=production
    restart: unless-stopped
    command: python -m src.frontend.app

  # Uncomment to add a database service if needed
  # db:
  #   image: postgres:13
  #   container_name: gaslit-af-db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=gaslit_af
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# Uncomment if using a database
# volumes:
#   postgres_data:
